### ISSUE TITLE
OpenAPI specification for backend

### ISSUE THREAD

**Issue by torokzs** [microsoft/PubSec-Info-Assistant#345]
**Is your feature request related to a problem? Please describe.**
Some customers would like to use only the backend part of IA and bring their own frontend. Also there is a requirement for APIM integration. 

**Describe the solution you'd like**
OpenAPI (Swagger) specification for the chat endpoint and other endpoints, in a same way like at the enrichmentweb app.

**Comment by dayland** [comment]
@torokzs, you can find in our vNext-Dev branch the recent PR #416 that will add Swagger documentation to our webapp backend services. This will be coming in a future release.

**Comment by dayland** [comment]
Resolved with latest release [v1.1](https://github.com/microsoft/PubSec-Info-Assistant/releases/tag/v1.1)
