### ISSUE TITLE
Token limit often exceeded with PDF files

### ISSUE THREAD

**Issue by TaylorN15** [microsoft/PubSec-Info-Assistant#353]
We have some large PDF files and during the chunking process, it seems to be often creating chunks that well exceed the "target size". For example, one document (which can be downloaded [here](https://budget.qld.gov.au/files/Budget_2023-24_BP4_Budget_Measures.pdf)), has one chunk over 80,000 tokens in length. 

There are several other chunks created from this same file that are smaller but still exceed the target size by a substantial amount.

**Comment by georearl** [comment]
resolved and included in the code base. Thank you TaylorN15

**Comment by TaylorN15** [comment]
> resolved and included in the code base. Thank you TaylorN15

@georearl - what if the table headers are larger than the chunk size as I mentioned earlier?
