### ISSUE TITLE
Secrets in plaintext in Deployment

### ISSUE THREAD

**Issue by michalmar** [microsoft/PubSec-Info-Assistant#360]
**Describe the bug**
I am getting sec policy violation that the deployment contains passwords.

**To Reproduce**
Deploy solution.

**Screenshots**
![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/16072588/f133c32c-c935-4f76-9ea0-62a5a6998461)

**Comment by Loo-Ree** [comment]
I've deployed last code version on the 20th of Dec but I've got this alerts: 
`Source:"/subscriptions/********************************/resourceGroups/in****/providers/Microsoft.Resources/deployments/storage-media"
Secret:"puWD***************"
RuleName:"AzureStorageAccountIdentifiableKey"
APIUrl:"/subscriptions/{0}/resourcegroups/{1}/providers/Microsoft.Resources/deployments?api-version=2021-04-01"
ExposureLocationId:"/subscriptions/********************************/resourceGroups/in****/providers/Microsoft.Resources/deployments/storage-media"`
Am I missing something? Thank you!
