### ISSUE TITLE
Support for M365 (SharePoint Online, OneDrive) content

### ISSUE THREAD

**Issue by nkidambi** [microsoft/PubSec-Info-Assistant#374]
**Issue at hand**
Almost all federal customers have big M365 presence. And have lots of documentation in SharePoint Online (SPO), and OneDrive. Few of my customers (VA, BEA, and NIH) have docs in SPO.

**A possible solution**
Extract and index documents and pages (site contents) in SPO and OneDrive using Graph SDK/REST

**Describe alternatives you've considered**
Other ways are to use LogicApps to get data from SPO, store them in blob and then use Cog Search.  It is very painful and adds complexity like data sync issues, duplicate storage, access and retention.

**Comment by georearl** [comment]
This is included as part of the planned 1.1 release. We do not include pages though, only documents.

**Comment by georearl** [comment]
This is resolved as part of the imminent 1.1 release
