### ISSUE TITLE
Error: Access denied due to invalid subscription key or wrong API endpoint

### ISSUE THREAD

**Issue by helpsystems-mushkevych** [microsoft/PubSec-Info-Assistant#439]
**Describe the bug**
After pulling most recent changes from the `main` branch and re-building and re-deploying the IA, i am observing following error:
```
Error: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.
```

**Comment by ryonsteele** [comment]
Hi, this was a bug that was just hot fixed. Please pull latest changes and re-run `make infrastructure`
It was a result of the wrong AOAI instance key being stored in the keyvault based on the useExistingAOAI flag.

**Comment by helpsystems-mushkevych** [comment]
thank you. works. please resolve the ticket
