### ISSUE TITLE
Document Intelligence returns tables with multiple table spans

### ISSUE THREAD

**Issue by ryonsteele** [microsoft/PubSec-Info-Assistant#463]
In some document edge cases, the spans for any given table index could have more than one span depending on the document, the table and it's layout. Until now we only handle the first span in the array.

If you see this and would like a fix, see the code changes made in this Pull Request for next version release 1.1
https://github.com/microsoft/PubSec-Info-Assistant/pull/462

**What is the expected behavior?**
For it to handle multiple spans if they exist

**Screenshots**
![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/17028127/2d69830e-36a5-4d51-9606-0ee249abae47)

### Information Assistant details
Affected versions v1.0

>GitHub branch: [e.g. main]
main

**Comment by dayland** [comment]
This was merged into main as a hotfix in #478.
