### ISSUE TITLE
Add a "Folder" column in the "Upload Status" tab of the "Manage Content" section of the Web App

### ISSUE THREAD

**Issue by marcopostmovares** [microsoft/PubSec-Info-Assistant#465]
Would it perhaps be possible to add an extra column called "Folder" in the "Upload Status" tab of the "Manage Content" section of the Web App? Sometimes, we upload the same file to multiple folders, but right now it is hard to track in the overview to which batch the file upload belongs.

**Comment by dayland** [comment]
@marcopostmovares, we are working on enhancing the "Manage Content" status page in our 1.1 release. We will add this to the backlog and likely include it as we are in there making changes. Thanks for the submission.

**Comment by georearl** [comment]
This has been included, along with many other new features, to the vNext-Dev branch which will be available in Main as part of the 1.1 release

**Comment by georearl** [comment]
resolved under imminent release of 1.1
