### ISSUE TITLE
Issues with documents filtering using tags

### ISSUE THREAD

**Issue by PaulineJaquot** [microsoft/PubSec-Info-Assistant#481]
Hi, 

We uploaded some files with multiple tags as seen below (e.g., project name: Wegstunnels AWA, project code: MN004259,  tender outcome: Gewonnen)
![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/89200604/df2fb540-7306-4b5d-8169-2ee338c65664)

When using these tags on the app frontend before querying the model, we got diverse errors:
- When selecting only one of the three tags, the completion always states that no data source is found (see below the completion, in Dutch sorry)
 
![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/89200604/2cea1d7f-4922-404f-977a-49273e034661)
![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/89200604/ed0187a8-0b7c-40ea-b09d-6339883f1f35)

- When selecting two or all three tags, we get instead an error:
![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/89200604/8318b304-9054-4415-a264-b956d3479c8f)
![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/89200604/b182ea6f-5074-441f-a963-632a35f97489)

 We have looked into the code and are struggling to pinpoint the reason why it fails. Could we get some support on this? 

The Git commit of the source code from this repo is: https://github.com/microsoft/PubSec-Info-Assistant/commit/27df39089a0a203c41ae153dc2539315559d0eeb 

Thank you!

**Comment by ryonsteele** [comment]
Hello - Found the issue here.
I have a solution in Pull Request https://github.com/microsoft/PubSec-Info-Assistant/pull/484
The issue being each tag was being quoted separately which was overloading the AZ Search function.
I made a change to normalize the parameter.

**Comment by PaulineJaquot** [comment]
That's great thank you, we'll try it out!

**Comment by PaulineJaquot** [comment]
Hi, we've just deployed the latest version of vNext-Dev (commit 0909c4b). The "Invalid Expression" error when using multiple tag is indeed gone, thank you! However, with one or multiple tag(s), the issue that no document source is found remains. If we query the database without any tag selected, we get an answer with citations. However, when we ask the same question but this time with one/multiple tag(s) selected, we get the message that no data source could be found (see screenshot in Dutch in previous message).

Is it this working well for you or other users?

**Comment by ryonsteele** [comment]
I think I have a better understanding of that search API and have an idea that should make searching with multiple tags way more accurate. Will update here when I have more.

**Comment by ryonsteele** [comment]
@PaulineJaquot The fix for this was not in the query this time but in the index itself.
The change exists in this PR https://github.com/microsoft/PubSec-Info-Assistant/pull/491
However, will require re-indexing of the source documents to correct the tags field.

**Comment by dayland** [comment]
Resolved with latest release [v1.1](https://github.com/microsoft/PubSec-Info-Assistant/releases/tag/v1.1)
