### ISSUE TITLE
npm severity vulnerability

### ISSUE THREAD

**Issue by asbanger** [microsoft/PubSec-Info-Assistant#482]
### Bug Details
**Describe the bug**
A high severity vulnerability has been identified in the codebase 
 
1 high severity vulnerability
 
To address all issues, run:
  npm audit fix
 
Run `npm audit` for details.

**Steps To Reproduce**

1. Access the code space
2. Run make deploy
3. Following warning has been highlighted when we run make deploy

**What is the expected behavior?**

**Screenshots**
![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/49021230/19d35bb2-9872-4e18-907f-da3661e4b8cf)
****

**Additional context**

**If the bug is confirmed, would you be willing to submit a PR?**

-  X] Yes
- [ ] No

**Comment by ryonsteele** [comment]
Not replicable

Ensure you have a recent version of NPM and/or run "npm audit" and provide those details.

![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/17028127/6f9c72f1-fe30-4e16-a39f-ba013e54ee62)

![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/17028127/12cf97e6-4874-4da0-83ba-642893c967fd)

![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/17028127/adfc0e7d-ab4f-4319-8c0a-765e69228b8e)
