### ISSUE TITLE
Chatbot answers error

### ISSUE THREAD

**Issue by rashodqaim** [microsoft/PubSec-Info-Assistant#483]
*Before you open an issue, please check if a similar issue already exists or has been closed before.*

 You can also find details on [Troubleshooting Common Issues](https://github.com/microsoft/PubSec-Info-Assistant/blob/main/docs/deployment/troubleshooting.md). You can use these tools to help gather additional logs and details to include in  your issue.

 :warning: Please DO NOT include confidential information in your issue on GitHub. :warning:

### Bug Details
**Describe the bug**
When asking a question in the web app to the Chatbot I get an error as an answer. Any question I ask I get the same error. 
**Steps To Reproduce**

1. Open web app link is here https://infoasst-web-jvrvm.azurewebsites.net/
2. Ask a question to the chatbot, an example question is "What is West Nile"
3. *** This is where the error happens we don't get an answer back just an error message***

**What is the expected behavior?**
The Expected behavior is an answer

**Screenshots**
![chatbot_error](https://github.com/microsoft/PubSec-Info-Assistant/assets/12738486/b2196be9-c229-4784-aebf-a8b46ee82180)

### Information Assistant details

Please provide the following details. You can simply include a screenshot of your Info panel as well.
![webapp_info](https://github.com/microsoft/PubSec-Info-Assistant/assets/12738486/6ae06b07-b3f0-451c-8f1b-deee3a14771a)

>GitHub branch: [e.g. main]
>deplyathon
>Version or Latest commit: [obtained by running `git log -n 1 <branchname>`
>None
>What region is your Azure Open AI Service in?
>East US
>What ChatGPT model are you using?
>Embedding
>model name: (i.e. gpt-3.5-turbo, gpt-4)
>GPT 35.Turbo
>model version: (i.e. 0613)
>0301
>What embeddings model are you using?
text-embedding-ada-002
**Additional context**

**If the bug is confirmed, would you be willing to submit a PR?**

- [ *] Yes
- [ ] No

**Comment by ArpitaisAn0maly** [comment]
Hello [rashodqaim](https://github.com/rashodqaim)

The error message indicates you have deployed text embedding model with deployment name 'textembeddingchatbot" which is not reachable through your enrichment app. It is not finding that model in enrichmentapp.

Can you please do two things.

1. Check azure open AI instance---> Deployments---> check the name of deployment for ada. Is it "textembeddingchatbot"?
2. open url of your enrichmentapp--->  make a post call to your embedding model---> are you able to do it?

**Comment by georearl** [comment]
Additionally can you validate the enrichment webapp exists and that it is started?

**Comment by rashodqaim** [comment]
The enrichmentapp was deleted, I will redeploy everything and hopefully that fixes it. Thank you
