### ISSUE TITLE
General question search support instead of documents only

### ISSUE THREAD

**Issue by ravikhunt** [microsoft/PubSec-Info-Assistant#487]
Hi There, Is there any support or planning to do the general question search instead of only from the documents that are uploaded
Sometimes someone needed to do the general search instead of documents. maybe it should be a toggle of dropdown selection to select what type of search you are looking for 
1) Document Search
2) General question Search 
3) Document  + General question search

**Comment by dayland** [comment]
@ravikhunt , Can you please provide a bit more detail by what you mean by "General Question Search"? Are you referring to something like Copilot with Bing (formerly Bing Chat) or just a generative response from the model like you get in AI Studio playground?

**Comment by ravikhunt** [comment]
Yes right generative response from the model like we get in the AI studio playground

The current scenario, it will only return results from uploaded documents, but if we want any common question answer like below it should return the result from a generative response as we have in screen2 below


![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/45026281/025d9a35-f090-4c41-b1b1-143ae75effeb)

**screen2**
![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/45026281/b9f8bd0c-913a-46d5-bdd2-486b492bb934)


So for that if we have something like two or three options that we can search with.

1) Data Chat
2) Generative Chat
3) Data + Generative chat  (it could be optional)
name is just for reference it could be any

**Comment by ravikhunt** [comment]
@dayland

**Comment by ravikhunt** [comment]
@dayland  Is there any update on this?

**Comment by bennyhartnett** [comment]
Great question

**Comment by dayland** [comment]
This feature is under development. We don't have an ETA yet. Will update once it has been groomed into a Sprint/Release.

**Comment by georearl** [comment]
We have included this in the backlog for the 1.1 release.

**Comment by dayland** [comment]
Resolved with latest release [v1.1](https://github.com/microsoft/PubSec-Info-Assistant/releases/tag/v1.1)
