### ISSUE TITLE
Azure Resource names not matching Azure Resource and unwanted/unused  resource are created.

### ISSUE THREAD

**Issue by nkidambi** [microsoft/PubSec-Info-Assistant#493]
### Bug Details

Deployment Branch: Main
** Bug 1: Names of App Settings and Azure Resources don't match
After deploying the main branch, the app settings for Azure Functions and the secret key in Azure Key Vault is referencing to Form Recognizer for a Document Intelligence Resource.   Also the name of the Document Intelligence Resource has "fr" in its name. This is causing some confusion because when the customer is searching for resources, they now have to use FR instead of document intelligence. 

This is causing confusion for my customer. 

** Bug 2: Unused resources created
Media Service and Azure AI Video Indexer are being created despite it not being used.  This is confusing and raising questions related to cost.

**What is the expected behavior?**
For Bug 1: The name to reflect the type of the resource created

For Bug 2: Not deploy/create unused/unwanted azure resources

**Screenshots**
![IA Bugs](https://github.com/microsoft/PubSec-Info-Assistant/assets/78823488/f3213bbf-368b-4081-99d7-a84942788954)

**Comment by georearl** [comment]
video indexer & media services is no longer created

**Comment by dayland** [comment]
Resolved with latest release [v1.1](https://github.com/microsoft/PubSec-Info-Assistant/releases/tag/v1.1)
