### ISSUE TITLE
Update Azure OpenAI Service preview API version

### ISSUE THREAD

**Issue by nhwkuhns** [microsoft/PubSec-Info-Assistant#496]
Azure OpenAI Service APIs 

- 2023-03-15-preview
- 2023-06-01-preview
- 2023-07-01-preview
- 2023-08-01-preview

will be retired on April 2, 2024. Information Assistant should be updated to use version 2023-12-01-preview.

Source [here](https://review.learn.microsoft.com/en-us/azure/ai-services/openai/api-version-deprecation?branch=main&branchFallbackFrom=pr-en-us-256331#latest-preview-api-release).

**Comment by ryonsteele** [comment]
I have tested updating to 2023-12-01-preview and will include in my infrastructure PR soon as the current plan

**Comment by dayland** [comment]
This will be addressed in our next release before the retirement of this version.

**Comment by dayland** [comment]
Resolved with latest release [v1.1](https://github.com/microsoft/PubSec-Info-Assistant/releases/tag/v1.1)
