### ISSUE TITLE
previous_paragraph_element_is_a_table' referenced before assignment 

### ISSUE THREAD

**Issue by shoresh57** [microsoft/PubSec-Info-Assistant#497]
{
                "status": "FileFormRecPollingPDF - An error occurred - code: 200 - local variable 'previous_paragraph_element_is_a_table' referenced before assignment",
                "status_timestamp": "2024-02-13 08:34:36",
                "status_classification": "Error",
                "stack_trace": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/threading.py\", line 973, in _bootstrap\n    self._bootstrap_inner()\n  File \"/usr/local/lib/python3.10/threading.py\", line 1016, in _bootstrap_inner\n    self.run()\n  File \"/usr/local/lib/python3.10/threading.py\", line 953, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.10/concurrent/futures/thread.py\", line 83, in _worker\n    work_item.run()\n  File \"/usr/local/lib/python3.10/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/azure-functions-host/workers/python/3.10/LINUX/X64/azure_functions_worker/dispatcher.py\", line 768, in _run_sync_func\n    return ExtensionManager.get_sync_invocation_wrapper(context,\n  File \"/azure-functions-host/workers/python/3.10/LINUX/X64/azure_functions_worker/extension.py\", line 215, in _raw_invocation_wrapper\n    result = function(**args)\n  File \"/home/site/wwwroot/FileFormRecPollingPDF/__init__.py\", line 145, in main\n    statusLog.upsert_document(blob_name, f\"{function_name} - An error occurred - code: {response.status_code} - {str(e)}\", StatusClassification.ERROR, State.ERROR)\n  File \"/home/site/wwwroot/FileFormRecPollingPDF/__init__.py\", line 104, in main\n    chunk_count = utilities.build_chunks(document_map, blob_name, blob_uri, CHUNK_TARGET_SIZE)\n  File \"/home/site/wwwroot/shared_code/utilities.py\", line 476, in build_chunks\n    previous_paragraph_element_is_a_table)\nUnboundLocalError: local variable 'previous_paragraph_element_is_a_table' referenced before assignment\n"
            }

another error

Message requed to embeddings queue, attempt 5. Visible in 1168 seconds. Error: Operation returned an invalid status 'The specified blob does not exist.'\nErrorCode:BlobNotFound."

**Comment by georearl** [comment]
We have replicated this issue. This occurs in processing PDF's which have large tabular data, where the large table is not prefixed with any content, such as text or titles. This would occur if you save an excel or CSV as a PDF then process. We are issuing a PR to our vNext-Dev branch in case you wish to use this change now. The PR is here #523
