### ISSUE TITLE
Chat History

### ISSUE THREAD

**Issue by destinychanger** [microsoft/PubSec-Info-Assistant#498]
Chat history Management would be a great feature if provided.

**Comment by ravikhunt** [comment]
@destinychanger  @ryonsteele 
https://github.com/microsoft/PubSec-Info-Assistant/issues/464

Is it similar to this right?

**Comment by destinychanger** [comment]
> @destinychanger @ryonsteele #464
> 
> Is it similar to this right?

Yes.
