### ISSUE TITLE
Integrate Content Safety API

### ISSUE THREAD

**Issue by paullizer** [microsoft/PubSec-Info-Assistant#506]
**Is your feature request related to a problem? Please describe.**
Govern the user prompts prior to sending requests to Azure AI Search and Azure OpenAI.

**Describe the solution you'd like**
Add a switch to the deployment to enable Content Safety, which would deploy the service and integrate it into the front end so that it analyzes user prompts prior to sending the request to Azure AI Search and Azure OpenAI.

**Describe alternatives you've considered**
Content filter is helpful but not as detailed of a solution as Content Safety. Content Safety reduces the need for OpenAI to govern its response and potentially reduces overall cost as user submissions that violate Content Safety policy will never be processed by Azure AI Search or Azure OpenAI.

**Additional context**
None.

**Comment by ArpitaisAn0maly** [comment]
hi [paullizer](https://github.com/paullizer)

AOAI content filtering is applicable to both prompt and completions

![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/55892521/aa1d44b9-7176-4fa4-98f7-a69b2cce85bb)

you can even add addiitonal content filtering on both prompt and completions

![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/55892521/43e78106-1acd-4dae-b967-d269ad25a4d9)

**Comment by paullizer** [comment]
That is content filtering with Block list. Which is processed by Azure OpenAI.

Content Safety is a separate service with its own API call with more comprehensive governance. This call would occur before generating the ada embedding, the request to Azure AI Search, and Azure OpenAI.

https://learn.microsoft.com/en-us/azure/ai-services/content-safety/overview



Respectfully,

Paul Lizer



Principal Technical Specialist

571-508-6416

Book time with Paul ***@***.***?anonymous&ep=pcard>

________________________________
