### ISSUE TITLE
WebApp not loading though Deployment is succesful

### ISSUE THREAD

**Issue by adnanakram82** [microsoft/PubSec-Info-Assistant#517]
Deployment states the webapp is deployed successfully and throws an exception. The web site does not load afterwards - please refer to screenshots below  
<img width="853" alt="image" src="https://github.com/microsoft/PubSec-Info-Assistant/assets/15710312/f8c647c1-2b98-449a-85b4-5f9108b1aa2f">
<img width="718" alt="image" src="https://github.com/microsoft/PubSec-Info-Assistant/assets/15710312/22126725-8445-4471-8695-3ded78db0384">

**Comment by LukaszJD** [comment]
I'm experiencing exactly the same issue

**Comment by LukaszJD** [comment]
Thanks @ryonsteele 
There are a few "AuthenticationFailed" in the log, would this be the cause of the issue?
![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/100772583/ca1fe83f-cfe0-43f4-a7cd-5a5cc015eccd)

**Comment by ryonsteele** [comment]
@LukaszJD It sure is. Thanks for providing that, a fix is in the works as I type.
