### ISSUE TITLE
Function APP deployment erroring out with Exception

### ISSUE THREAD

**Issue by adnanakram82** [microsoft/PubSec-Info-Assistant#521]
Web App issue WebApp not loading though Deployment is succesful #517  (https://github.com/microsoft/PubSec-Info-Assistant/issues/517) has been fixed but now the issue is with the Function App. Similar issues and now the files get stuck in the processing Queue and dont move forward.
![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/15710312/45c3973c-adca-4fe6-a7b7-4ce3f83ae683)
![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/15710312/65af4069-ef3b-4a11-9a24-6feba5b66bfb)

**Comment by ryonsteele** [comment]
I believe this is related to #519 I'm about to put in a hotfix for this shortly if you will try again once merged.
If not just reopen this issue and let us know.
