### ISSUE TITLE
Reopeing: Issue 521 (Function App Exception at Deployment time)

### ISSUE THREAD

**Issue by adnanakram82** [microsoft/PubSec-Info-Assistant#526]
Function App deployment is not working. Although it mentions that the function app has been deployed successfully, but there are an exception. On using the accelerator now when I upload data it gets stuck in Queue state. See the screen shot below. I restarted the function app, but it does not work.  

![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/15710312/56560412-03dc-4e4c-9dd1-645a3e4bc79c)
![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/15710312/7691041d-6109-45a3-bcc7-3ac22678e8dc)

**Comment by ryonsteele** [comment]
Hello. This is not enough actionable information.
Please review the documentation here to further explore the issue you are having.
https://github.com/microsoft/PubSec-Info-Assistant/blob/main/docs/deployment/troubleshooting.md

Best guess, based on the behavior, is that your enrichment web app is not runing.
