### ISSUE TITLE
Launch Profile dropdown 

### ISSUE THREAD

**Issue by developer992** [microsoft/PubSec-Info-Assistant#532]
From documentation: https://github.com/microsoft/PubSec-Info-Assistant/blob/main/docs/deployment/configure_local_dev_environment.md

`From this windows use the Launch Profile dropdown to open the Ubuntu 22.04 (WSL) terminal. image`

Where is this button?

**Comment by ryonsteele** [comment]
Hello. That button exists here:

![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/17028127/0d8c8cfa-f102-42cd-8e5c-7a0fac2dc8cc)

https://code.visualstudio.com/docs/terminal/profiles

**Comment by developer992** [comment]
Thanks!
