### ISSUE TITLE
can you mount folder or do you litterally have to clone repo inside wsl dev container?

### ISSUE THREAD

**Issue by developer992** [microsoft/PubSec-Info-Assistant#533]
title

**Comment by ryonsteele** [comment]
Yes, mounting a folder with the repo to the ubuntu wsl would function the same as cloning on the repo.

**Comment by dayland** [comment]
The challenge will be if you mount a Windows folder into the Ubuntu environment file permissions and pathing some times do not translate properly within the WSL environment and can conflict with some of our automation scripts as they assume Linux file system.

**Comment by developer992** [comment]
this app doesn't work on Linux nor Windows

IT LITTERALL DOESNT WORK

**Comment by dayland** [comment]
@developer992 , our recomended approach is to use GitHub CodeSpace so you don't need to clone anything to your local machine. Please see the deployment guide at https://github.com/microsoft/PubSec-Info-Assistant/blob/main/docs/deployment/deployment.md#development-environment-configuration

**Comment by mstevesmith** [comment]
Man this guy has been blowing up github with cursing and spazzing out

**Comment by developer992** [comment]
i like to keep it local

**Comment by developer992** [comment]
hej @michael, i wouldn't have to if this crap worked

**Comment by dayland** [comment]
A reminder to all to please observe our Community Code of Conduct policies. https://opensource.microsoft.com/codeofconduct/. We are happy to support on issues but abusive or derogatory comments will not be allowed!

**Comment by dayland** [comment]
This issue is marked for closure due to inactivity for 2 weeks. It will be closed in 5 days.
