### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by developer992** [microsoft/PubSec-Info-Assistant#542]
from enrichment\requirements.txt

`azure.search.documents==11.4.0b11`

This doesn't exist, there is only this:

azure-search-documents 11.4.0 

which results in

```
    from approaches.chatreadretrieveread import ChatReadRetrieveReadApproach
  File "/app/approaches/chatreadretrieveread.py", line 16, in <module>
    from azure.search.documents.models import RawVectorQuery
ImportError: cannot import name 'RawVectorQuery' from 'azure.search.documents.models' (/root/.cache/pypoetry/virtualenvs/aila-9TtSrW0h-py3.11/lib/python3.11/site-packages/azure/search/documents/models/__init__.py)
```

**Comment by developer992** [comment]
they're also not in azure-cli installed with apt-get

**Comment by developer992** [comment]
honestly, the richest company in the world can't afford a couple of python seniors

honestly, we're not that expensive

**Comment by developer992** [comment]
it's like this is MICROSOFTS first python project

i remember how ugly mine was

amazing

**Comment by developer992** [comment]
also not here

https://learn.microsoft.com/en-us/python/api/azure-search-documents/azure.search.documents.models?view=azure-python

**Comment by developer992** [comment]
https://learn.microsoft.com/en-us/java/api/com.azure.search.documents.models.rawvectorquery?view=azure-java-preview 404

**Comment by developer992** [comment]
404 https://learn.microsoft.com/en-us/python/api/azure-search-documents/azure.search.documents.models.rawvectorquery?view=azure-python-preview

**Comment by developer992** [comment]
apparently java skd has it https://azuresdkdocs.blob.core.windows.net/$web/java/azure-search-documents/11.6.0-beta.10/com/azure/search/documents/models/RawVectorQuery.html

**Comment by developer992** [comment]
https://github.com/search?q=repo%3AAzure%2Fazure-sdk-for-python%20RawVectorQuery&type=code


found this, apparently was renamed ... the old package isn't available anymore and nobody at microsoft THE RICHEST COMPANY IN THE WORLD cared enough to update your own STUPID CASH COW APP 

amazing, trully remarkable

**Comment by developer992** [comment]
i think this is MICROSOFTS silent approach to get people off python

WHY CANT YOU JUST USE .NET right ? ?? 

truly a shame for a company of your size

**Comment by dayland** [comment]
This version is available at https://pypi.org/project/azure-search-documents/11.4.0b11/

**Comment by developer992** [comment]
yeah why does pip install fail then
