### ISSUE TITLE
Image is taking up 13GB and doesn't even work

### ISSUE THREAD

**Issue by developer992** [microsoft/PubSec-Info-Assistant#546]
Docker WSL is taking up over 300 GB !!!! 

I uninstalled Ubuntu

AND IT STILL TAKING UP SPACE

HOW DO I REMOVE THIS ?

**Comment by dayland** [comment]
If WSL is hogging up memory and CPU on your machine you can control it's behaviors using https://learn.microsoft.com/en-us/windows/wsl/wsl-config. 

As for cleaning up any cached docker images you can reference... https://docs.docker.com/config/pruning/
