### ISSUE TITLE
Loading module from “http://127.0.0.1:9000/src/index.tsx” was blocked because of a disallowed MIME type (“application/octet-stream”).

### ISSUE THREAD

**Issue by developer992** [microsoft/PubSec-Info-Assistant#550]
Where is this coming from ?

**Comment by developer992** [comment]
if i change this 

<script type="module" src="/src/index.tsx"></script>
to this

ž

**Comment by dayland** [comment]
We are not familiar with this error. It appears to be a local machine policy. If you use the GitHub Codespace as recommended in deployment this should not occur. https://github.com/microsoft/PubSec-Info-Assistant/blob/main/docs/deployment/deployment.md#development-environment-configuration

**Comment by developer992** [comment]
i see where the problem is

you guys keep forgetting there was a python world before microsoft adopted it
