### ISSUE TITLE
embeddings

### ISSUE THREAD

**Issue by developer992** [microsoft/PubSec-Info-Assistant#556]
If this setting USE_AZURE_OPENAI_EMBEDDINGS is False then the code fails with

```
Traceback (most recent call last):
  File "/app/app.py", line 204, in chat
    r = impl.run(request.json["history"], request.json.get("overrides") or {})
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/approaches/chatreadretrieveread.py", line 207, in run
    raise Exception('Error generating embedding:', response.status_code)
Exception: ('Error generating embedding:', 403)
```

And if it's True, it fails with 

```
  File "/app/app.py", line 155, in <module>
    embedding_model_name = embedding_deployment.properties.model.name
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'model'
```

Related settings i have no idea what to do with

AZURE_OPENAI_EMBEDDINGS_MODEL_NAME
AZURE_OPENAI_EMBEDDINGS_VERSION

probably others as well ...

**Comment by dayland** [comment]
You need to follow the instructions for populating all the parameters in you `local.env`. See https://github.com/microsoft/PubSec-Info-Assistant/blob/main/docs/deployment/deployment.md#configure-env-files

You can also see examples of the values in `scripts/environments/local.env.example`. 

The values for AZURE_OPENAI_EMBEDDINGS_MODEL_NAME and AZURE_OPENAI_EMBEDDINGS_VERSION are not required. They will be dynamically pulled from Azure Management Plane APIs at runtime in most cases.
