### ISSUE TITLE
Not able to deploy the code

### ISSUE THREAD

**Issue by mranil053** [microsoft/PubSec-Info-Assistant#573]
we are not able to deploy the code through GitHub codespace getting the error-

InvalidTemplateDeployment - The template deployment 'infoasst-ifitechdemo1' is not valid according to the validation procedure. The tracking id is 'a20904d3-cb53-4d76-b0c3-4326687af536'. See inner errors for details.
ResourceKindRequireAcceptTerms - This subscription cannot create CognitiveServices until you agree to Responsible AI terms for this resource. You can agree to Responsible AI terms by creating a resource through the Azure Portal then trying again. For more detail go to https://aka.ms/csrainotice

**Comment by dayland** [comment]
https://github.com/microsoft/PubSec-Info-Assistant/blob/main/docs/knownissues.md#this-subscription-cannot-create-azureiaservices-until-you-agree-to-responsible-ai-terms-for-this-resource

**Comment by dayland** [comment]
This issue is marked for closure due to inactivity for 2 weeks. It will be closed in 5 days.
