### ISSUE TITLE
Azure Gov Deployment: App Registration Redirect URI pointing to ".net" instead of ".us"

### ISSUE THREAD

**Issue by nkidambi** [microsoft/PubSec-Info-Assistant#597]
### Bug Details
**Describe the bug**
After deploying the main branch to Azure Gov, launching the main web app displays the error shown in the attachment.

**Steps To Reproduce**

1. Follow instructions to deploy to Azure Gov
2. Launch main web app
3. Accept permissions and you should the error.

**What is the expected behavior?**
The web app loads with no error

** Proposed solution
Update the redirect URI for Azure Gov deployments to point to ".us"

**Screenshots**

### Information Assistant details

Please provide the following details. You can simply include a screenshot of your Info panel as well.

GitHub branch: [e.g. main]
 main

What region is your Azure Open AI Service in?
Azure Gov - usgovvirginia

What ChatGPT model are you using?
 gpt-4

model name: (i.e. gpt-3.5-turbo, gpt-4)
gpt-4 1106-preview
 
![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/78823488/5177345d-a9a6-4536-be88-d387b3db6e3f)

**Comment by dayland** [comment]
Resolved with latest release [v1.1](https://github.com/microsoft/PubSec-Info-Assistant/releases/tag/v1.1)
