### ISSUE TITLE
File still stuck on Queued

### ISSUE THREAD

**Issue by rashodqaim** [microsoft/PubSec-Info-Assistant#635]
This is the same issue that I was having as issue number #580. I pulled from the main branch this morning (04/09/2024) and deployed. I uploaded the two files I was having issues with and got the same results. Attached is a screenshot showing this, if there is anything else you would like me to add please let me know. 
![chatbot_error_april_9](https://github.com/microsoft/PubSec-Info-Assistant/assets/12738486/e4744a89-b8fe-474f-95d3-7550365d3a2b)

**Comment by georearl** [comment]
Hi there. We use unstructured.io to process csv json etc. An older version that we had locked on was not chunking these files correctly. A few weeks back we issued an update to our Main branch with an update that resolved this. Can you do a pull from Main, redeploy and try these files again. In the meantime, I will close this., but feel free to reopen.

**Comment by rashodqaim** [comment]
Hi, I created a brand new deployment using the latest GitHub main branch and still get the error. Here is a screenshot showing the updated requirement txt file. Can we reopen this ticket and take a look at this again??
![requirement_error](https://github.com/microsoft/PubSec-Info-Assistant/assets/12738486/085fdc3c-02e5-4004-865a-5377a760cb82)
