### ISSUE TITLE
Queued Error when uploading Json or CSV 

### ISSUE THREAD

**Issue by rashodqaim** [microsoft/PubSec-Info-Assistant#651]
Hi, this is the same issue I had with #635 and #580. I was able to upload a PDF that was 4164 KB but a 19000 KB CSV got stuck on Queued again, as well as an 8000KB JSON file. I have pulled the latest Main GitHub branch as seen in the attachment. But I am not sure what I am doing incorrectly because, in the latest update, I was just instructed to pull the latest Main GitHub Branch, redeploy and that would have solved this issue. Please let me know if there is anything else that I should be doing or if you need me to explain this in more detail
![requirement_error](https://github.com/microsoft/PubSec-Info-Assistant/assets/12738486/8fd805d0-f1e9-4ba8-96b8-5edac621d071)

.

**Comment by cscdiniz** [comment]
I am having the same issue. Has it been solved yet? Thanks

**Comment by georearl** [comment]
please verify after a fresh make deploy. We upgraded unstructured.io and this fixed the issue with chunking large csv and json files. Ideally try 1.1

**Comment by rashodqaim** [comment]
I will deploy today and update you with the results
