### ISSUE TITLE
Deployment error for V1.1 : CredentialInvalidLifetimeAsPerAppPolicy: Credential lifetime exceeds the max value allowed as per assigned

### ISSUE THREAD

**Issue by smallangi** [microsoft/PubSec-Info-Assistant#681]
While deploying V1.1, I get the following error. where can I change the Credential lifetime? 
*********************

module.searchServices.azurerm_key_vault_secret.search_service_key: Creating...
module.searchServices.azurerm_key_vault_secret.search_service_key: Creation complete after 0s [id=https://infoasst-kv-ldbie.vault.azure.net/secrets/AZURE-SEARCH-SERVICE-KEY/XXXXXXXXXXXXXXXXXXXXXXXXXXX]
╷
│ Error: Adding password for application with object ID "XXXXXXXXXXXXXXXXXXXXXX"
│ 
│   with module.entraObjects.azuread_application_password.aad_mgmt_app_password[0],
│   on core/aad/entra.tf line 33, in resource "azuread_application_password" "aad_mgmt_app_password":
│   33: resource "azuread_application_password" "aad_mgmt_app_password" {
│ 
│ ApplicationsClient.BaseClient.Post(): unexpected status 400 with OData error:
│ CredentialInvalidLifetimeAsPerAppPolicy: Credential lifetime exceeds the max value allowed as per assigned
│ policy '538f1913-366a-440a-95a0-e195cb55b282'.
╵
make: *** [Makefile:25: infrastructure] Error 1

**Comment by smallangi** [comment]
Hi IA Team!  This works fine in another environment where I have more privileges. IA deployed with no issues in new env. This is low priority issue. I ran into this issue only with V1.1 . May be the Azure Account permissions section needs to be updated with relevant info.

**Comment by dayland** [comment]
As a temporary fix while we are preparing a hotfix for this... you can add a line to control the credential lifetime. 

```terraform
end_date = timeadd(timestamp(), "4380m")
```
just after line 36 in `infra/core/aad/entra.tf`
