### ISSUE TITLE
Increase maximum question length

### ISSUE THREAD

**Issue by PaulineJaquot** [microsoft/PubSec-Info-Assistant#694]
Hi, 

In the frontend, the maximum question length is set at 1000 characters. This seems to be defined in the "app\frontend\src\components\QuestionInput\QuestionInput.tsx" module. Our users would like to write larger prompts. Is it possible to manually increase the maximum length without any impact on the processing of the query ?

**Comment by dayland** [comment]
You can simply update the code to increase the size a user can enter. You need to be aware of the Max Request (tokens) for the model you are using. Assuming you are using a model with a large enough Max Request (tokens) then you will be ok. 

You can find the full list of token capacity per model at https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models

**Comment by PaulineJaquot** [comment]
Perfect, thanks !
