### ISSUE TITLE
Access to Sharepoint subfolders in UI

### ISSUE THREAD

**Issue by PaulineJaquot** [microsoft/PubSec-Info-Assistant#695]
Hi,

We have synced two Sharepoint folders containing themselves several subfolders when deploying v1.1. following the instructions in the documentation. When looking in the storage account in "Upload" or "Content" all seems in order, we can see the expected folder structure. 
![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/89200604/69890d5e-83e9-4ee6-aa1b-9abf8169fe1f)

However when trying to select a folder in the UI, it appears that only the root Sharepoint folder can be selected. This is not very useful for us this way. Is there a specific setup to follow or if it is planned as future improvement? 

![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/89200604/625a4c6e-022c-4905-bf6e-381f4f6a53c6)

**Comment by KronemeyerJoshua** [comment]
Hey there! Sorry you're having some issues with this, let's see if I can clear some things up. :)

As part of our SharePoint ingestion process, folders are meant to be listed as part of the SHAREPOINT_TO_SYNC variable in your environment configuration file when you deploy. Any changes made in the Logic App UI will be overwritten as it reads from a configuration file created upon deployment.

If you've already deployed, no worries! The config.json where your SHAREPOINT_TO_SYNC environment variable was written can be found in your blob storage under the config container, it's called "config.json"

To list multiple folders within the same sharepoint site, you'll need to have two entries for the site, each one pointing to a different folder.

Example
[
{ "url": "https://yoursharepoint.com", "folder": "/Shared Documents/YourFolder"},
{ "url": "https://yoursharepoint.com", "folder": "/Shared Documents/YourFolder2"}
]

If you're updating the config.json file directly, do not forget to mirror those changes to your environment configuration SHAREPOINT_TO_SYNC variable so your changes won't be lost if you decide to deploy again.

More information regarding environment variables can be found here: https://github.com/microsoft/PubSec-Info-Assistant/blob/main/docs/deployment/deployment.md

More information regarding SharePoint can be found here: 
https://github.com/microsoft/PubSec-Info-Assistant/blob/main/docs/features/sharepoint.md

Let me know if this helps clarify things or if you need more assistance.

**Comment by dayland** [comment]
@PaulineJaquot , this is how it is designed at the moment. Only top level folders in the Azure Blob Storage Container "upload" show in the "Folders" dropdown on both the Manage Content > Upload page and the Adjust Panel on Chat. You are welcome to clone the repo and extend the logic to read deeper into the folder tree if you would like. 

We do not currently have any items on the backlog to extend this feature, however, you are welcome to submit a Feature request under the "Issues" tab on the repo.

**Comment by PaulineJaquot** [comment]
Hi ok clear, thanks for your answer :)
