### ISSUE TITLE
What are the steps to redeploy after changing the UI ?

### ISSUE THREAD

**Issue by reshma67** [microsoft/PubSec-Info-Assistant#704]

**Comment by georearl** [comment]
Hi. could you elaborate a bit? I assume you have made some code level changes to the webapp? If that is the case you can run a full make deploy, or be more surgical and just run make build-deploy-webapp. If your changes included anything at the infrastructure level, such as configuration values, then you would need to also run make infrastructure if these were added to the Terraform code.

**Comment by reshma67** [comment]
make deploy has worked
