### ISSUE TITLE
How to upgrade from gpt-35-turbo-16k to gpt-4o

### ISSUE THREAD

**Issue by rashodqaim** [microsoft/PubSec-Info-Assistant#744]
I have a simple question, I am trying to upgrade the IA tool from gpt-35-turbo-16k to gpt-4o, without creating a whole new IA tool. There is already a lot of data inside the tool and people using it, so I don't want to deploy a new IA tool add the information back in and give everyone access to it again. The CodeSpace I use to create this is shut down as well. Documentation on how to this upgrade would be perfect.

**Comment by dayland** [comment]
Switching out GPT models is fairly easy to do on a running IA system. It involves the following steps:

1. Log into the Azure Portal
2. Navigate to the IA web app App Service (infoasst-web-xxxxx). 
3. Open the **Environment Variables** or **Configuration** blade (depends on the Azure Portal version)
4. Update the following settings with the new values you want to target
    - `AZURE_OPENAI_CHATGPT_DEPLOYMENT` (required)
    - You only need to update the following if you provided these in your `local.env`
       - `AZURE_OPENAI_CHATGPT_MODEL_NAME`
       - `AZURE_OPENAI_CHATGPT_MODEL_VERSION`
5. Save the settings changes.
6. Navigate back to the **Overview** blade and Restart the App Service. 

Once the App Service has restarted the web app should be up and using your new model deployment. 

*NOTE: You will need to manually deploy the "gpt-4o" model to your instance of Azure OpenAI. IA does not currently support deploying gpt-4o model directly.*

**Comment by Fipeek** [comment]
I think I have follow-up question for this ticket. Yesterday I tried to change the open AI service that I use in the infoasst-web app service. I changed the env variables: 

-  AZURE_OPENAI_ENDPOINT -> the endpoint URL in Azure Open AI service where gpt4o is deployed
- AZURE_OPENAI_SERVICE -> the name of the new Azure Open AI service 
- AZURE_OPENAI_SERVICE_KEY -> key to my new Azure Open AI Service endpoint
- AZURE_OPENAI_CHATGPT_DEPLOYMENT -> deployment name of my gp4o
 
However after the restart I'm getting application error, also on the other hand I noticed that my Azure AI service and previous (created by initial deployment) Azure Open AI service is using the same Endpoint URL

**Comment by rayxfelipe** [comment]
I am also seeing errors and inconsistencies when updating env variables.

**Comment by dayland** [comment]
If your Azure OpenAI instance is in another resource group, you may need to assign permissions to read properties from it. 

Assign the role "Cognitive Services OpenAI User" to the service principal named "infoasst_mgmt_access_xxxx" on the resource group or AOAI instance.

**Comment by Fipeek** [comment]
My OpenAI instance is in the same resource group but it's another instance (not the initial one create by the make deploy script)

**Comment by jdnuckolls** [comment]
I was getting an application error because the App Service (infoasst-web-xxxxxx) try to launch the site.  Looks like the container could not start after changing the Environment Variable to gpt-4o.  It worked for a bit, but then started erroring out.  Attached is a snapshot of the log file.
![error-gpt4o](https://github.com/user-attachments/assets/6cc1875f-2d7e-495a-927e-3167542edcbc)

**Comment by supplemarty** [comment]
@dayland I think the utilities file in functions/shared_code needs to be updated to use the proper encoding for token count when switching to gpt4o cl100k_base is hard coded

**Comment by dayland** [comment]
This was fixed in the recent v1.2 release. https://github.com/microsoft/PubSec-Info-Assistant/releases/tag/v1.2
