### ISSUE TITLE
Azure DevOps Pipeline or GitHub Action for deploying the solution as IaC

### ISSUE THREAD

**Issue by Anand-Moghe** [microsoft/PubSec-Info-Assistant#747]
We have customers trying to deploy this solution in Azure Gov Cloud. And the deployment is supported in Azure Public cloud.

So I was wondering if we can deploy this solution as Azure DevOps Pipeline or GitHub Action as IaC?
Can you add additional steps and information in that respect in this repository?

**Comment by dayland** [comment]
@Anand-Moghe , the solution already supports deployment to US Gov cloud via Azure DevOps pipelines. We currently run CI/CD on US Gov for all PRs. Example pipelines are included in the `/pipelines` folder. 

https://github.com/microsoft/PubSec-Info-Assistant/blob/main/docs/deployment/setting_up_sandbox_environment.md

**Comment by Anand-Moghe** [comment]
Thanks @dayland
