### ISSUE TITLE
Instructure for setting up sandbox environment is outdate

### ISSUE THREAD

**Issue by DevPaulLiu** [microsoft/PubSec-Info-Assistant#748]
### Bug Details
In [*Configuring Azure Active Directory Objects*](https://github.com/microsoft/PubSec-Info-Assistant/blob/main/docs/deployment/setting_up_sandbox_environment.md#configuring-azure-active-directory-objects) in setting_up_sandbox_environment.md, it mentioned there are some AAD objects need to be created through create-ad-objs-fordeployment.sh, however the script is no longer exist. The instructions need to be updated.

**Steps To Reproduce**

1. go to https://github.com/microsoft/PubSec-Info-Assistant/blob/main/docs/deployment/setting_up_sandbox_environment.md#configuring-azure-active-directory-objects
2. In step#2, Navigate to the /scripts folder and run the create-ad-objs-for-deployment.sh script manually.

The create-ad-objs-for-deployment.sh no longer exist, and it's not clear what variables it will output.

**What is the expected behavior?**
Expected to get a clear explanation regarding the variables need to be set in ADO Pipeline
**Screenshots**
![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/57442833/2c4678b1-9076-43ee-8dff-9a81c067c75f)

**Comment by dayland** [comment]
Thank you for this feedback, we will update and push a hotfix. This changed when we moved to Terraform in v1.1.
