### ISSUE TITLE
Few-shot examples with energy conservation are used in prompts when chatting ungrounded with the models

### ISSUE THREAD

**Issue by nhwkuhns** [microsoft/PubSec-Info-Assistant#766]
### Bug Details
When chatting ungrounded, directly with the model, it will occasionally give responses based on the few-shot examples used for the grounded chats.

**Steps To Reproduce**

1. Start an ungrounded chat
2. Send the prompt "test test"

**What is the expected behavior?**
The model would typically reply with something like "it appears you are trying to test something. If you give me more context I can help"

**Screenshots**
![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/85817913/047aec82-ad4a-46f6-af75-5fac6269d5e0)

### Information Assistant details

Please provide the following details. You can simply include a screenshot of your Info panel as well.

>GitHub branch: main
> main
>Version or Latest commit:
>v1.1.1 commit e60ed3e6dced43796a96d9b2115b4c283872a0eb
>What region is your Azure Open AI Service in? 
>EastUS
>What ChatGPT model are you using?
>gpt-4o
>model name: (i.e. gpt-3.5-turbo, gpt-4)
>gpt-4o
>model version: (i.e. 0613)
>2024-05-13
>What embeddings model are you using?
>BAAI/bge-small-env-v1.5

**Additional context**

**If the bug is confirmed, would you be willing to submit a PR?**

- [X] Yes
- [ ] No

**Comment by dayland** [comment]
@nhwkuhns , I have put in a PR for this. It will get updated in our next release.
