### ISSUE TITLE
Unused/duplicate function purge_soft_deleted_blob

### ISSUE THREAD

**Issue by TaylorN15** [microsoft/PubSec-Info-Assistant#780]
This seems to be a copy/paste of the preceding function `get_deleted_blobs` with a different name, but it's not used anywhere...

https://github.com/microsoft/PubSec-Info-Assistant/blob/16ff7504ad2fa62fbca21ce4a82a2e62fecf3aa1/functions/FileDeletion/__init__.py#L59

**Comment by ChaitanyaYeole02** [comment]
Hey @dayland, I am interested to work on this issue. Can you please assign it to me?
