### ISSUE TITLE
azure-ai-vision == 0.15.1b1 - this release has been yanked

### ISSUE THREAD

**Issue by asbanger** [microsoft/PubSec-Info-Assistant#804]
*Before you open an issue, please check if a similar issue already exists or has been closed before.*

 You can also find details on [Troubleshooting Common Issues](https://github.com/microsoft/PubSec-Info-Assistant/blob/main/docs/deployment/troubleshooting.md). You can use these tools to help gather additional logs and details to include in  your issue.

 :warning: Please DO NOT include confidential information in your issue on GitHub. :warning:

### Bug Details
**Describe the bug**
The release version azure-ai-vision 0.15.1b1 has been yanked. This is causing issues with dependencies listed in the requirements.txt file of the repository.

https://github.com/microsoft/PubSec-Info-Assistant/blob/main/functions/requirements.txt.

**Steps To Reproduce**

1.Clone the repository from PubSec-Info-Assistant
2. Navigate to the functions directory.
3. .Run pip install -r requirements.txt.

**What is the expected behavior?**

**Screenshots**

### Information Assistant details

Please provide the following details. You can simply include a screenshot of your Info panel as well.

>GitHub branch: [e.g. main]
>
>Version or Latest commit: [obtained by running `git log -n 1 <branchname>`
>
>What region is your Azure Open AI Service in?
>
>What ChatGPT model are you using?
>
>model name: (i.e. gpt-3.5-turbo, gpt-4)
>
>model version: (i.e. 0613)
>
>What embeddings model are you using?

**Additional context**

**If the bug is confirmed, would you be willing to submit a PR?**

- [ ] Yes
- [ ] No

**Comment by bjakems** [comment]
We will be upgrading to 1.0.0b2.
