### ISSUE TITLE
US Gov deployment failing with error message " polling failed" for Azure AI Search

### ISSUE THREAD

**Issue by ArpitaisAn0maly** [microsoft/PubSec-Info-Assistant#810]
US Gov deployment for IA failing with below error message. The error is happening in make infrastructure step.

This is happening in both US Arizona and US Virginia region. (US Texas has other restrictions on cognitive services so unable to test or deploy there.)

<img width="286" alt="image" src="https://github.com/user-attachments/assets/05921efa-cdb2-4ebb-90f1-8424b06e52aa">
I am able to create standalone Azure AI search resource in both regions. so confirming there is no capacity or any other issue of Azure AI search in both regions.

**Comment by dayland** [comment]
Resolved in Azure, without need for code change. Assumes to be capacity issues.
