### ISSUE TITLE
Cognitive Services is not the same as AI services [Bing Enrichment needs extra steps]

### ISSUE THREAD

**Issue by neurartbcc** [microsoft/PubSec-Info-Assistant#835]
*Before you open an issue, please check if a similar issue already exists or has been closed before.*

 You can also find details on [Troubleshooting Common Issues](https://github.com/microsoft/PubSec-Info-Assistant/blob/main/docs/deployment/troubleshooting.md). You can use these tools to help gather additional logs and details to include in  your issue.

 :warning: Please DO NOT include confidential information in your issue on GitHub. :warning:

### Bug Details
**Describe the bug**

There is a diferent API call for AI services, and for Bing Enrichment, which means you ALSO have to create and accept the terms for Azure AI Services multi-service account. without it, you get the error: 

Resource Group Name: "infoasst-neurartpubs"
│ Account Name: "infoasst-enrichment-cog-uxkyk"): unexpected status 400 with error: ResourceKindRequireAcceptTerms: This subscription cannot create CognitiveServices until you agree to Responsible AI terms for this resource. You can agree to Responsible AI terms by creating a resource through the Azure Portal then trying again. For more detail go to https://aka.ms/csrainotice

Please recognize this is **not** the AI services error, but the CognitiveServices error for the API call

**Steps To Reproduce**

1. create new sub
2. make deploy with correct local.env
4. ...

**What is the expected behavior?**

**Screenshots**

### Information Assistant details

Please provide the following details. You can simply include a screenshot of your Info panel as well.

>GitHub branch: [e.g. main]
>
>Version or Latest commit: [obtained by running `git log -n 1 <branchname>`
>
>What region is your Azure Open AI Service in?
>
>What ChatGPT model are you using?
>
>model name: (i.e. gpt-3.5-turbo, gpt-4)
>
>model version: (i.e. 0613)
>
>What embeddings model are you using?

**Additional context**

**If the bug is confirmed, would you be willing to submit a PR?**

- [ ] Yes
- [ ] No

**Comment by dayland** [comment]
This is documented in the known issues at https://github.com/microsoft/PubSec-Info-Assistant/blob/main/docs/knownissues.md#this-subscription-cannot-create-azureaiservices-until-you-agree-to-responsible-ai-terms-for-this-resource. 

Azure AI Services (formerly Azure Cognitive Services) require this once per subscription. This is not the same as Azure Open AI Services nor Azure Bing Search APIs, as those are separate services.

**Comment by neurartbcc** [comment]
It is not though, that's why I'm bringing it up with the tags. You have to create **both** an AI services **AND** an Azure AI Services multi-service account. Notice the diference in both the icon and kind in the attached screenshot. 

Of course, you could just add to the know problems the extra step of making both, but that's the whole point I'm raising. You'll need to accept both terms. 

Note this is a new sub and a new tenant so the **IMPORTANT** flag in the know issues can also be ammended to add this.
![AI Services](https://github.com/user-attachments/assets/a4b06b80-c40b-4c4a-8627-4a158b95a0f0)

**Comment by dayland** [comment]
Interesting, thanks for calling this out as we have not seen this before. That is not how it is "supposed" to work AFIK. I will assign an engineer to investigate and update any docs accordingly.

**Comment by bjakems** [comment]
The documentation has been updated to reflect the need for both account terms.
