### ISSUE TITLE
When trying to deploy in different regions we hit the error: This region has quota of 0 PremiumV3 cores for your subscription

### ISSUE THREAD

**Issue by MYSdeployment** [microsoft/PubSec-Info-Assistant#888]
We face this issue when we try to deploy in regions eastus2 and uksouth. 

│ Error: creating App Service Plan (Subscription: "69945115-588c-49d7-b8fa-d6df86685294"
│ Resource Group Name: "infoasst-digitallibrary"
│ Server Farm Name: "infoasst-enrichmentasp-uqneu"): performing CreateOrUpdate: unexpected status 401 (401 Unauthorized) with response: {"Code":"Unauthorized","Message":"This region has quota of 0 PremiumV3 cores for your subscription. Try selecting different region or SKU.","Target":null,"Details":[{"Message":"This region has quota of 0 PremiumV3 cores for your subscription. Try selecting different region or SKU."},{"Code":"Unauthorized"},{"ErrorEntity":{"ExtendedCode":"52039","MessageTemplate":"{0}. Try selecting different region or SKU.","Parameters":["This region has quota of 0 PremiumV3 cores for your subscription"],"Code":"Unauthorized","Message":"This region has quota of 0 PremiumV3 cores for your subscription. Try selecting different region or SKU."}}],"Innererror":null}
│ 
│   with module.enrichmentApp.azurerm_service_plan.appServicePlan,
│   on core/host/enrichmentapp/enrichmentapp.tf line 2, in resource "azurerm_service_plan" "appServicePlan":
│    2: resource "azurerm_service_plan" "appServicePlan" {
│ 
│ creating App Service Plan (Subscription: "69945115-588c-49d7-b8fa-d6df86685294"
│ Resource Group Name: "infoasst-digitallibrary"
│ Server Farm Name: "infoasst-enrichmentasp-uqneu"): performing CreateOrUpdate: unexpected status 401 (401 Unauthorized) with response: {"Code":"Unauthorized","Message":"This region has quota of 0 PremiumV3 cores for your subscription. Try selecting different region or
│ SKU.","Target":null,"Details":[{"Message":"This region has quota of 0 PremiumV3 cores for your subscription. Try selecting different region or SKU."},{"Code":"Unauthorized"},{"ErrorEntity":{"ExtendedCode":"52039","MessageTemplate":"{0}. Try selecting different region or SKU.","Parameters":["This region
│ has quota of 0 PremiumV3 cores for your subscription"],"Code":"Unauthorized","Message":"This region has quota of 0 PremiumV3 cores for your subscription. Try selecting different region or SKU."}}],"Innererror":null}
╵

**Comment by bjakems** [comment]
Hello,

Please either send a request to add more quota to your subscription or downgrade to the below SKUs (please don't scale below the SKUs provided below as these are the minimum required).

I've found that the centralus and uksouth regions typically have the most SKU availability for these items.

export TF_VAR_functionsAppSkuSize="S2"
export TF_VAR_functionsAppSkuTier="Standard"
export TF_VAR_appServiceSkuSize="S1"
export TF_VAR_appServiceSkuTier="Standard"
export TF_VAR_enrichmentAppServiceSkuSize="S3"
export TF_VAR_enrichmentAppServiceSkuTier="Standard"

**Comment by bjakems** [comment]
Please add these to your local.env file.  If you do not have one, there is an example base that you can use as a base and create the local.env file in the same directory.  Please see the image for an example.
![Image](https://github.com/user-attachments/assets/79e74abf-df0d-4a86-9c19-913366d8aadd)

**Comment by MYSdeployment** [comment]
Hello,

I added the rows which you provide to us and now we have successful deployment in UK South region.

Thank you for your cooperation!
