### ISSUE TITLE
ImportError: cannot import name 'cached_download' from 'huggingface_hub'  causing enrichment to be unhealthy

### ISSUE THREAD

**Issue by KevinDMack** [microsoft/PubSec-Info-Assistant#893]
### Bug Details
When deploying the info-assistant, we are seeing the enrichment application never becomes healthy.  This is due to the container image throwing the following error.

ImportError: cannot import name 'cached_download' from 'huggingface_hub' 

This error then causes any new file upload to stop at the enrichments step and messages not to be picked up from the queue.  

**Steps To Reproduce**

1. Setup local.env file
2. Run make deploy
3. Go to the resource group
4. Select the enrichment app
5. Select log stream

**What is the expected behavior?**
I would expect the app to come up as healthy, and process the requests.  After doing some research, the fix for this would be the following:

update /app/enrichment/requirements.txt:
sentence-transformers>=2.3.0

Additionally, this was very hard to debug and identify, as I had to upload documents, and identify that it was taking to long, check queues, and ultimately check the health of the enrichment app.  And I noticed a couple of things during this process. 

1. The enrichments application is not connected to the Application Insights instance, only the function app is.  
2. The UI on the website just hangs and it makes it hard to identify an issue.

What would be more helpful, is if all 3 app services were instrumented in Application Insights, and if the UI on the website could give a visual ping, or a status update to indicate before submission that the backend dependency is unhealthy and unusable.  

Please provide the following details. You can simply include a screenshot of your Info panel as well.

>GitHub branch: [e.g. main]  main
>
>Version or Latest commit: [obtained by running `git log -n 1 <branchname>`
>Merge: 1038af55 c24adbd8
>Author: dayland <48474707+dayland@users.noreply.github.com>
>Date:   Mon Oct 14 10:58:30 2024 +0100
>Merge pull request #878 from miriambrus/docupdates
>doc updates
>What region is your Azure Open AI Service in?
>usgovvirginia
>What ChatGPT model are you using?
>gpt-4
>model name: (i.e. gpt-3.5-turbo, gpt-4)
>gpt-4
>model version: (i.e. 0613)
>
>What embeddings model are you using?
ada-002
**Additional context**

**If the bug is confirmed, would you be willing to submit a PR?**

- [ ] Yes
- [ ] No

**Comment by bjakems** [comment]
Hi @KevinDMack ,
Thanks for reporting this issue.  The team is aware and currently working on a fix.  I will comment back to this issue once the resolution is in the main branch.

**Comment by bjakems** [comment]
The issue has been resolved and is in the main branch.

To update your 1.2 IA deployment, enter the same deployment Codespace, etc that the Terraform state assets are saved, then run the below commands in your terminal.
git checkout main
git pull
make build-deploy-enrichments

**Comment by edoublec** [comment]
Same error still in 1.1. I tried deploying 1.2 and had countless problems
